import os

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 2')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 5')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 8')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 11')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 14')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 17')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 20')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 23')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 26')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 29')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 32')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 35')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 38')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 41')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 44')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 47')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 50')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 53')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 56')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 59')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 62')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 65')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 68')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 71')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 74')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 77')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 80')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 83')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 86')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 89')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 92')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 95')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 98')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 101')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 104')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 107')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 110')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 113')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 116')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 119')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 122')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 125')

print('ALL DONE')
