import os

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 1')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 4')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 7')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 10')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 13')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 16')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 19')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 22')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 25')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 28')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 31')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 34')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 37')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 40')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 43')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 46')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 49')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 52')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 55')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 58')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 61')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 64')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 67')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 70')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 73')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 76')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 79')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 82')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 85')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 88')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 91')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 94')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 97')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 100')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 103')

print('ALL DONE')
