import os

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 2')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 5')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 8')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 11')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 14')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 17')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 20')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 23')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 26')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 29')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 32')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 35')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 38')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 41')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 44')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 47')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 50')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 53')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 56')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 59')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 62')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 65')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 68')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 71')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 74')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 77')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 80')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 83')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 86')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 89')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 92')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 95')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 98')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 101')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 104')

print('ALL DONE')
