import os

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 1')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 4')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 7')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 10')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 13')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 16')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 19')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 22')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 25')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 28')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 31')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 34')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 37')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 40')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 43')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 46')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 49')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 52')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 55')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 58')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 61')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 64')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 67')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 70')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 73')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 76')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 79')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 82')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 85')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 88')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 91')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 94')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 97')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 100')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 103')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 106')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 109')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 112')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 115')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 118')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 121')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 124')

print('ALL DONE')
