import os

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 3')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 6')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 9')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 12')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 15')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 18')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 1 --sens_weight 1 --flat_weight 1 --seed 21')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 24')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 27')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 30')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 33')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 36')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 39')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 2 --sens_weight 1 --flat_weight 1 --seed 42')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 45')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 48')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 51')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 54')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 57')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 60')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 3 --sens_weight 1 --flat_weight 1 --seed 63')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 66')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 69')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 72')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 75')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 78')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 81')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 4 --sens_weight 1 --flat_weight 1 --seed 84')

os.system('python optimize.py --open_frac 0.3 --hole_limit 11 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 87')
os.system('python optimize.py --open_frac 0.35 --hole_limit 14 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 90')
os.system('python optimize.py --open_frac 0.4 --hole_limit 17 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 93')
os.system('python optimize.py --open_frac 0.45 --hole_limit 30 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 96')
os.system('python optimize.py --open_frac 0.5 --hole_limit 50 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 99')
os.system('python optimize.py --open_frac 0.55 --hole_limit 107 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 102')
os.system('python optimize.py --open_frac 0.6 --hole_limit 300 --corr_weight 5 --sens_weight 1 --flat_weight 1 --seed 105')

print('ALL DONE')
