import os

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 3')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 6')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 9')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 12')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 15')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 18')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 21')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 24')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 27')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 30')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 33')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 36')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 39')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.4 --seed 42')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 45')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 48')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 51')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 54')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 57')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 60')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.4 --seed 63')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 66')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 69')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 72')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 75')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 78')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 81')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 84')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 87')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 90')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 93')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 96')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 99')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 102')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 2 --sens_weight 1 --flat_weight 2 --frac_tetris 0.6 --seed 105')

os.system('python optimize.py --open_frac 0.3 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 108')
os.system('python optimize.py --open_frac 0.35 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 111')
os.system('python optimize.py --open_frac 0.4 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 114')
os.system('python optimize.py --open_frac 0.45 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 117')
os.system('python optimize.py --open_frac 0.5 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 120')
os.system('python optimize.py --open_frac 0.55 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 123')
os.system('python optimize.py --open_frac 0.6 --balanced --corr_weight 1 --sens_weight 2 --flat_weight 2 --frac_tetris 0.6 --seed 126')

print('ALL DONE')
